### ISSUE TITLE
Visual studio extension not work completly

### ISSUE THREAD

**Issue by SongOfYouth** [unoplatform/studio#27]
### Current behavior

- the output window error : `Failed to retrieve the solution's loaded NuGet packages. Make sure a full NuGet restore has completed properly and reload the solution.`
- sporadic debug error on windows: `Failed to create a 'System.Type' from the text 'local:DiagnosticsOverlay'. [Line: 9 Position: 3]`,if continue all things is ok.
- the indicator status on web, and no any effect when click the button: 
![image](https://github.com/user-attachments/assets/4c0bb127-647f-4aa5-a387-2ef33bdc1577)

### Which tool(s) are affected?

Hot Reload

### IDE used

Visual Studio 2022

### IDE version

17.12.3

### Uno Platform Extension version

5.5.53.78

### Anything else we need to know?

tried measures：
- uninstall the uno platform extension and reinstall it.
- delete the bin/obj folder and rebuild all project
- run with admin or not
- enable all the debug options of .net/c++
- start the website by chrome and edge
- start with debug mode or not

**Comment by jeromelaban** [comment]
Thanks for the report.

We need additional logs:
- In `Tools`, `Options`, `Projects and Solutions`, for the `MSBuild project output verbosity`, set it to `Diagnostics`
- Restart Visual Studio
- Open the output window, (`View`, `Output`), then select the `Uno Platform` in the drop down list.
- Open your Uno Platform solution project

Can you share this window output in this issue?

Also, can you create a zip of the project that you created and share it here?

Thanks for your help!

**Comment by SongOfYouth** [comment]
After multiple attempts, I realized that this was because I manually specified the local cache path for Nuget in the `Nuget.config` file! when I set it to default, it works!

**Comment by sasakrsmanovic** [comment]
Should this be closed then @SongOfYouth ?
